default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: graduation_app_development
  cable:
    <<: *default
    database: graduation_app_development

test:
  primary:
    <<: *default
    database: graduation_app_test
  cable:
    <<: *default
    database: graduation_app_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
