default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  primary:
    <<: *default
    database: graduation_app_development

  cache:
    <<: *default
    database: graduation_app_development

  queue:
    <<: *default
    database: graduation_app_development

  cable:
    <<: *default
    database: graduation_app_development

test:
  primary:
    <<: *default
    database: graduation_app_test

  cache:
    <<: *default
    database: graduation_app_test

  queue:
    <<: *default
    database: graduation_app_test

  cable:
    <<: *default
    database: graduation_app_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
